config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "videos#index"
  resources :users, only: [:edit, :update, :show]
  resources :videos, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: :create
    collection do
      get 'search'
    end
    member do
      get 'category'
    end
  end
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre

  validates :video_name, presence: true
  validates :video_url, format: {with: /\A(https:\/\/)(www.youtube.com\/watch\?v=|youtu\.be\/)+[a-zA-Z0-9\-_]{11}\z/, message:"にはYouTube動画URLを入力してください" }
  validates :overview, presence: true
  validates :genre_id, presence: true, numericality: { other_than: 1, message:"を選択してください" }

  def self.search(search)
    if search != "" && search != " " && search != "　"
      Video.where('video_name LIKE(?) || overview LIKE(?)', "%#{search}%", "%#{search}%").order("created_at DESC")
    else
      Video.includes(:user).order("created_at DESC")
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search, :category]
  before_action :set_video, except: [:index, :new, :create, :search, :category]
  before_action :move_to_index, only: [:edit, :update, :destroy]
  
  def index
    @video = Video.includes(:user).order("created_at DESC")
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.create(video_params)
    if @video.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @video.comments.includes(:user).order("created_at DESC")
    @replies = @comments
  end

  def edit
  end

  def update
    if @video.update(video_params)
      redirect_to video_path(@video)
    else
      render :edit
    end
  end

  def destroy
    if @video.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def search
    if params[:keyword].present?
      @keyword = params[:keyword]
      split_keywords = (params[:keyword]).split(/[[:blank:]]+/)
      @videos = Video
      split_keywords.each do |keyword|
        @videos = @videos.search(keyword)
      end
      @videos = @videos.includes(:user)
    else
      @videos = Video.search(params[:keyword])
    end
  end

  def category
    if params[:id].to_i > 1 && params[:id].to_i < 23
    @videos = Video.where(genre_id: params[:id]).includes(:user).order("created_at DESC")
    @genre = Genre.find(params[:id])
    else
      redirect_to root_path
    end
  end

  private

  def video_params
    params.require(:video).permit(:video_name, :video_url, :overview, :genre_id, :image).merge(user_id: current_user.id)
  end

  def set_video
    @video = Video.find(params[:id])
  end

  def move_to_index
    unless current_user == @video.user
      redirect_to root_path
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_with model: video, local: true do |f|%>

  <%= render 'layouts/error_messages', model: f.object %>
  
  <div class="field">
    <%= f.label :video_name, "動画名" %><br />
    <%= f.text_field :video_name, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :video_url, "動画URL" %><br />
    <%= f.text_field :video_url, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :overview, "動画概要" %><br />
    <%= f.text_area :overview, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :genre_id, "動画ジャンル" %><br />
    <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, ) %>
  </div>

  <div class="field", id= "youtube_image">
    <%= f.label :image, "サムネイル画像（任意）" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="image-preview" id="image-preview"></div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/videos/_video.html.erb
<div class="card">
  <% if video.image.present? %>
    <%= link_to image_tag(video.image, class: :card__img ), video_path(video)%>
  <% else %>
    <%= link_to image_tag("no_image.png", class: :card__img), video_path(video)%>
  <% end %>
  <div class="card__body">
    <%= link_to video.video_name, video_path(video), class: :card__title%>
    <p class="card__summary">
      <%= video.genre.name %>
    </p>
  </div>
  <div class="user__body">
    <%= link_to "by #{video.user.channel_name}", user_path(video.user), class: :card__user %>
  </div>
</div>

app/views/videos/category.html.erb
<main class="main">
  <div class="inner">
    <div class="genre_result">
    「<%= "#{@genre.name}" %>」の動画PR
    </div>
    <div class="card__wrapper">
      <% @videos.each do |video| %>
        <%= render partial: "video", locals: { video: video }%>
      <% end %>
    </div>
    <div class="to-top", id="to-top">
      <%= "⇧" %>
    </div>
  </div>
</main>

app/views/videos/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">動画PR投稿編集</h2>
      <%= render partial: "form", locals: { video: @video } %>
    </div>
  </div>
</div>

app/views/videos/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        こんにちは、
        <%= link_to "#{current_user.channel_name}さん", user_path(current_user), class: :greeting__link%>
      </div>
    <% end %>
    <%= form_with(url: search_videos_path, local: true, method: :get, class: "search-form") do |f| %>
      <%= f.text_field :keyword, placeholder: "検索", class: "search-input" %>
      <%= f.submit "検索", class: "search-btn" %>
    <% end %>
    <div class="card__wrapper">
      <%= render partial: "video", collection: @video %>
    </div>
    <div class="to-top", id="to-top">
      <%= "⇧" %>
    </div>
  </div>
</main>

app/views/videos/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規動画PR投稿</h2>
        <%= render partial: "form", locals: { video: @video } %>
    </div>
  </div>
</div>

app/views/videos/search.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        こんにちは、
        <%= link_to "#{current_user.channel_name}さん", user_path(current_user), class: :greeting__link%>
      </div>
    <% end %>
    <%= form_with(url: search_videos_path, local: true, method: :get, class: "search-form") do |f| %>
      <%= f.text_field :keyword, placeholder: "検索",  value: @keyword, class: "search-input" %>
      <%= f.submit "検索", class: "search-btn" %>
    <% end %>
    <div class="search_result">
    <% if @keyword.present? && @videos.present? %>
      「<%= "#{@keyword}" %>」の検索結果
    <% elsif @videos.empty? %>  
      「<%= "#{@keyword}" %>」に一致する検索結果はありません
    <% end %>
    </div>
    <div class="card__wrapper">
      <% @videos.each do |video| %>
        <%= render partial: "video", locals: { video: video }%>
      <% end %>
    </div>
    <div class="to-top", id="to-top">
      <%= "⇧" %>
    </div>
  </div>
</main>

app/views/videos/show.html.erb
<main class="main">
  <div class="inner">
    <div class="video__wrapper">
      <p class="video__hedding">
        <%= @video.video_name%>
      </p>

      <div class="video_user__body">
        <%= link_to "by #{@video.user.channel_name}", user_path(@video.user), class: :video__user %>
      </div>

      <% if current_user == @video.user %>
        <div class="video__manage">
          <%= link_to "編集する", edit_video_path(@video), class: :video__btn %>
          <%= link_to "削除する", video_path(@video), method: :delete, class: :video__btn, data: { confirm: "この投稿を削除しますか？"} %>
        </div>
      <% end %>

      <div class="video__image">
        <% if @video.image.present? %>
          <%= image_tag @video.image %>
        <% else %>
          <%= image_tag "no_image.png" %>
        <% end %>
      </div>
      <div class="video__link">
        <%= link_to "<動画視聴はこちら>", "#{@video.video_url}",target: :_blank, rel: "noopener noreferrer" %>
      </div>
      <div class="video__body">
        <div class="video__detail">
          <p class="detail__title">動画ジャンル</p>
          <p class="detail__message">
            <%= @video.genre.name %>
          </p>
        </div>
        <div class="video__detail">
          <p class="detail__title">動画概要</p>
          <p class="detail__message">
            <%= text_url_to_link(simple_format(@video.overview)).html_safe %>
          </p>
        </div>
      </div>
      <div class="sns" >
        <p class="sns__title">SNSで共有</p>
        <%= link_to (image_tag "twitter_logo.png", class: :sns__img), "https://twitter.com/intent/tweet?text=#{@video.video_name}#{@video.video_url}",target: :_blank, rel: "noopener noreferrer" %>
        <%= link_to (image_tag "facebook_logo.png", class: :sns__img), "https://www.facebook.com/share.php?u=#{@video.video_url}",target: :_blank, rel: "noopener noreferrer" %>
        <%= link_to (image_tag "line_logo.png", class: :sns__img), "https://social-plugins.line.me/lineit/share?url=#{@video.video_url}",target: :_blank, rel: "noopener noreferrer" %>
      </div>
      <div>
        <%= link_to "#{@video.genre.name}の動画PRをもっと見る", category_video_path(@video.genre.id), class: :genre__btn %>
      </div>
      <div class="video__comments">
        <% if user_signed_in? %>
          <%= form_with model: [@video, @comment], local: true do |f|%>
            <div class="field">
              <%= f.label :text, "コメント" %><br />
              <%= f.text_field :text %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %> 
        <% end %> 
        <ul class="comments_lists">
          <% @comments.each do |comment|%>
            <% if comment.reply_comment_id.nil? %>
            <li class="comments_list">
              <div class="comment">
              <%= text_url_to_link(comment.text).html_safe%>
              <%= link_to "（#{comment.user.channel_name}）", user_path(comment.user), class: :comment_user %>
              </div>
                <ul class="reply_lists">
              <% @replies.each do |reply|%>
                <% if reply.reply_comment_id == comment.id%>
                  <li class="reply_list">
                    <%= text_url_to_link(reply.text).html_safe%>
                    <%= link_to "（#{reply.user.channel_name}）", user_path(reply.user), class: :comment_user %>
                  </li>
                <% end %> 
              <% end %> 
                </ul>
              <% if user_signed_in? %>
                <%= form_with model: [@video, @comment], local: true do |f|%>
                  <div class="reply_field">
                    <%= f.text_field :text %>
                    <%= f.hidden_field :reply_comment_id, value: comment.id  %>
                  </div>
                  <div class="reply">
                    <%= f.submit "返信する", class: :form__btn  %>
                  </div>
                <% end %> 
              <% end %> 
            </li>
            <% end %> 
          <% end %>
        </ul>
      </div>
    </div>
    <div class="to-top", id="to-top">
      <%= "⇧" %>
    </div>
  </div>
</main>