config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: "videos#index"
  resources :users, only: [:edit, :update, :show]
  resources :videos, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: :create
    collection do
      get 'search'
    end
    member do
      get 'category'
    end
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>NewTuber</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="red">
          <div class="red__left">
            <%= link_to image_tag("logo3.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="red__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :red__logout %>
              <%= link_to "New Video", new_video_path, class: :red__btn %>
            </div>
          <% else %>
            <div class="red__right">
              <%= link_to "ログイン", new_user_session_path, class: :red__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :red__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © SHOTA KAWASAKI All rights reserved.</p>
    </footer>
  </body>
</html>